# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crop.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(537, 47)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self._time_range_lb = QtWidgets.QLabel(self.centralwidget)
        self._time_range_lb.setMinimumSize(QtCore.QSize(100, 25))
        self._time_range_lb.setMaximumSize(QtCore.QSize(100, 25))
        self._time_range_lb.setObjectName("_time_range_lb")
        self.horizontalLayout.addWidget(self._time_range_lb)
        spacerItem = QtWidgets.QSpacerItem(14, 22, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self._tmin_le = QtWidgets.QLineEdit(self.centralwidget)
        self._tmin_le.setMinimumSize(QtCore.QSize(120, 25))
        self._tmin_le.setMaximumSize(QtCore.QSize(120, 25))
        self._tmin_le.setAlignment(QtCore.Qt.AlignCenter)
        self._tmin_le.setObjectName("_tmin_le")
        self.horizontalLayout.addWidget(self._tmin_le)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self._tmax_le = QtWidgets.QLineEdit(self.centralwidget)
        self._tmax_le.setMinimumSize(QtCore.QSize(120, 25))
        self._tmax_le.setMaximumSize(QtCore.QSize(120, 25))
        self._tmax_le.setAlignment(QtCore.Qt.AlignCenter)
        self._tmax_le.setObjectName("_tmax_le")
        self.horizontalLayout.addWidget(self._tmax_le)
        spacerItem1 = QtWidgets.QSpacerItem(14, 22, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self._start_btn = QtWidgets.QPushButton(self.centralwidget)
        self._start_btn.setMinimumSize(QtCore.QSize(93, 25))
        self._start_btn.setMaximumSize(QtCore.QSize(93, 25))
        self._start_btn.setObjectName("_start_btn")
        self.horizontalLayout.addWidget(self._start_btn)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self._time_range_lb.setText(_translate("MainWindow", "Time Range (s)"))
        self.label_2.setText(_translate("MainWindow", "-"))
        self._start_btn.setText(_translate("MainWindow", "Start"))
        self._start_btn.setShortcut(_translate("MainWindow", "Return"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
