# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'list.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(116, 654)
        MainWindow.setMinimumSize(QtCore.QSize(116, 654))
        MainWindow.setMaximumSize(QtCore.QSize(116, 654))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self._list_widget = QtWidgets.QListWidget(self.centralwidget)
        self._list_widget.setMinimumSize(QtCore.QSize(90, 600))
        self._list_widget.setMaximumSize(QtCore.QSize(90, 16777215))
        self._list_widget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self._list_widget.setMovement(QtWidgets.QListView.Static)
        self._list_widget.setResizeMode(QtWidgets.QListView.Adjust)
        self._list_widget.setLayoutMode(QtWidgets.QListView.SinglePass)
        self._list_widget.setViewMode(QtWidgets.QListView.ListMode)
        self._list_widget.setSelectionRectVisible(False)
        self._list_widget.setObjectName("_list_widget")
        self.verticalLayout.addWidget(self._list_widget)
        self._ok_btn = QtWidgets.QPushButton(self.centralwidget)
        self._ok_btn.setMinimumSize(QtCore.QSize(90, 25))
        self._ok_btn.setMaximumSize(QtCore.QSize(90, 25))
        self._ok_btn.setObjectName("_ok_btn")
        self.verticalLayout.addWidget(self._ok_btn)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self._list_widget.setSortingEnabled(False)
        self._ok_btn.setText(_translate("MainWindow", "OK"))
        self._ok_btn.setShortcut(_translate("MainWindow", "Return"))

    @property
    def list_widget(self):
        return self._list_widget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
