# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resample.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(474, 47)
        MainWindow.setMinimumSize(QtCore.QSize(474, 47))
        MainWindow.setMaximumSize(QtCore.QSize(474, 47))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self._resampling_rate_lb = QtWidgets.QLabel(self.centralwidget)
        self._resampling_rate_lb.setMinimumSize(QtCore.QSize(141, 25))
        self._resampling_rate_lb.setMaximumSize(QtCore.QSize(141, 25))
        self._resampling_rate_lb.setObjectName("_resampling_rate_lb")
        self.horizontalLayout.addWidget(self._resampling_rate_lb)
        spacerItem = QtWidgets.QSpacerItem(17, 17, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self._resampling_rate_le = QtWidgets.QLineEdit(self.centralwidget)
        self._resampling_rate_le.setMinimumSize(QtCore.QSize(150, 25))
        self._resampling_rate_le.setMaximumSize(QtCore.QSize(150, 25))
        self._resampling_rate_le.setEchoMode(QtWidgets.QLineEdit.Normal)
        self._resampling_rate_le.setAlignment(QtCore.Qt.AlignCenter)
        self._resampling_rate_le.setObjectName("_resampling_rate_le")
        self.horizontalLayout.addWidget(self._resampling_rate_le)
        spacerItem1 = QtWidgets.QSpacerItem(17, 17, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self._start_btn = QtWidgets.QPushButton(self.centralwidget)
        self._start_btn.setMinimumSize(QtCore.QSize(93, 25))
        self._start_btn.setMaximumSize(QtCore.QSize(93, 25))
        self._start_btn.setObjectName("_start_btn")
        self.horizontalLayout.addWidget(self._start_btn)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self._resampling_rate_lb.setText(_translate("MainWindow", "Resampling Rate(Hz)"))
        self._start_btn.setText(_translate("MainWindow", "Start"))
        self._start_btn.setShortcut(_translate("MainWindow", "Return"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
